name: ReportGUI
author: Taylcd Edit By haKingdomsCraft

version: 1.1.0
api:
  - 3.0.0
  - 4.0.0
  - 3.0.0-ALPHA9
  - 3.0.0-ALPHA10
  - 3.0.0-ALPHA11
  - 3.0.0-ALPHA12

main: Taylcd\ReportGUI\ReportGUI
depend: ["FormAPI"]

commands:
  report:
    description: Report a player
    permission: report.use
  reportadmin:
    description: Open Report Panel
    permission: report.admin

permissions:
  report.use:
    default: true
  report.admin:
    default: op
